apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: btgy931wa-go 
  janus-idp.io/tekton: btgy931wa-go
  backstage.io/kubernetes-id: btgy931wa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: btgy931wa-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  